config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    attr_accessible :title, :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def show
        @article = Article.find(params[:id])
    end
    def new
        @articles = Article.new
    end
    def create
        @article = Article.new(params[:article])
        if @article.save
            redirect_to_@article
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/new.html.erb
<h1>Nuevo articulo</h1>

<%= form_for(@article) do |f| %>
        <div class="field">
            <%= f.label :title %>
            <%= f.text_field :title %>
        </div>
        <div class="field">
            <%= f.label :content %>
            <%= f.text_area :content %>
        </div>
        <div class="action">
            <%= f.submit %>
        </div>
<% end %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <b>Title: </b>
    <%= @article.title %>
</p>
<p>
    <b>Cuerpo</b>
    <%= @article.content %>
</p>
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>